version: "3.7"

services:
  client:
    build:
      context: .
    command: yarn serve --mode development --port 8080 --dashboard
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    environment:
      - CHOKIDAR_USEPOLLING=true
